// <auto-generated by="the Blazor I18n Text compiler" />
namespace Jellyfin.Blazor.Shared.I18nText
{
    public partial class Text : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Sign in"</summary>
        public string LoginButton;

        /// <summary>"Host"</summary>
        public string LoginHost;

        /// <summary>"https://jellyfin.domain.tld"</summary>
        public string LoginHostPlaceholder;

        /// <summary>"Password"</summary>
        public string LoginPassword;

        /// <summary>"An unknown error occurred"</summary>
        public string LoginUnknownError;

        /// <summary>"Username"</summary>
        public string LoginUsername;
    }
}
