name: Build WASM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup dotnet environment
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # tag=v2
        with:
          dotnet-version: 6.0.x
          
      - name: Setup node environment
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version: 16 
        
      - name: Install node dependencies
        run: npm ci --no-audit
        working-directory: ./src/Jellyfin.Blazor.Shared
        
      - name: Build WASM
        run: dotnet build --configuration Release
        working-directory: ./src/Jellyfin.Blazor.Wasm