name: Build iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-12
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2

      - name: Setup .NET
        uses: actions/setup-dotnet@608ee757cfcce72c2e91e99aca128e0cae67de87 # tag=v1
        with:
          dotnet-version: 6.0.x

      - name: Setup node environment
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # tag=v2.1.5
        with:
          node-version: 16 
      
      - name: Install Maui Workload
        run: dotnet workload install maui
        
      - name: Install node dependencies
        run: npm ci --no-audit
        working-directory: ./src/Jellyfin.Blazor.Shared
        
      - name: Build
        working-directory: ./src/Jellyfin.Blazor.Maui
        run: dotnet build -c Release -f net6.0-ios
