name: Build Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Setup .NET
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # tag=v2
        with:
          dotnet-version: 6.0.x

      - name: Setup node environment
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version: 16 
      
      - name: Generate version number using date and run number
        shell: pwsh
        id: version-creator
        run: |
          $buildDay = Get-Date -Format "yyyy.Mdd"
          $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
          echo "::set-output name=APP_VERSION::$ver"

      - name: Install Maui Workload
        run: dotnet workload install maui

      - name: Install node dependencies
        run: npm ci --no-audit
        working-directory: ./src/Jellyfin.Blazor.Shared
        

      - name: Build
        working-directory: ./src/Jellyfin.Blazor.Maui
        shell: pwsh
        run: |
          dotnet build -c Release -f net6.0-windows10.0.19041.0
          dotnet publish -c Release -f net6.0-windows10.0.19041.0
          New-Item -Path .. -Name "artifacts" -ItemType Directory
          Get-ChildItem -Path Jellyfin.Maui*.msix -Recurse -File | Copy-Item -Destination ..\artifacts\

      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: windows-v${{ steps.version-creator.outputs.APP_VERSION }}-artifacts
          path: |             
            .\src\artifacts\Jellyfin.Maui*.msix
