name: Build iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-12
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Setup .NET
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8 # tag=v2
        with:
          dotnet-version: 6.0.x

      - name: Setup node environment
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version: 16 
      
      - name: Install Maui Workload
        run: dotnet workload install maui
        
      - name: Install node dependencies
        run: npm ci --no-audit
        working-directory: ./src/Jellyfin.Blazor.Shared
        
      - name: Build
        working-directory: ./src/Jellyfin.Blazor.Maui
        run: dotnet build -c Release -f net6.0-ios
