name: Publish WASM

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Setup node environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14 
        
      - name: Install node dependencies
        run: npm ci --no-audit
        working-directory: ./src/Jellyfin.Blazor.Shared
        
      - name: Build WASM
        run: dotnet build --configuration Release
        working-directory: ./src/Jellyfin.Blazor.Wasm

      - name: Publish WASM
        run: dotnet publish --configuration Release -o dist --nologo
        working-directory: ./src/Jellyfin.Blazor.Wasm

      - name: Push to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./src/Jellyfin.Blazor.Wasm/dist/wwwroot